baseURL       = "https://sugarstage.netlify.app/"
languageCode  = "en-us"
title         = "SugarTime Waxing Studio"
theme         = "roxo"
summarylength = 25

# Site Menus
[menu]
    # Navbar Menus
    [[menu.nav]]
        name    = "Home"
        url     = ""
        weight  = 1
    [[menu.nav]]
        name    = "About"
        url     = "about"
        weight  = 2
    [[menu.nav]]
        name    = "Services"
        url     = "services"
        weight  = 3
    [[menu.nav]]
        name    = "FAQ's"
        url     = "faq"
        weight  = 4
    [[menu.nav]]
        name    = "Book Now"
        url     = "contact"
        weight  = 5

# Site Params
[params]
  logo = "images/logo.png"
  dateFormat = "26 FEB 1994"
  # Meta data
  description = "SugarTime Waxing Studio"
  author = "SugarTime"
  # Google Analitycs
  googleAnalitycsID = "Your ID"
  # We're using formspree.io for form handling, paste your formspree url below
  formspreeFormUrl  = "https://formspree.io/myykjpje"

  # Contact Form
  [params.contactForm]
    placeholder_first_name        = "First Name"
    placeholder_last_name         = "Last Name"
    placeholder_email             = "Email"
    placeholder_project_type      = "Project Type"
    placeholder_about_the_project = "About the Project"
    send_message                  = "Send Message"

    [[params.contactForm.projectType]]
      value = "gd"
      title  = "Graphics Design"
    [[params.contactForm.projectType]]
      value = "wd"
      title  = "Web Design"

  # Navbar Action Button
  [params.navAction]
    status  = true
    name    = "Book Now"
    url     = "contact"

  [params.banner]
    enable                = true
    background_image      = "images/backgrounds/hero-background.jpg"
    heading               = "A clean, organic, hair removal studio providing a pleasant & comfortable experience"
    tagline               = ""
    primary_button        = "Do’s & Dont’s"
    primary_button_url    = "dos-and-donts"
    secondary_button      = "Book Appt"
    secondary_button_url  = "contact"

  [params.services]
    enable    = true
    background_image    = "images/backgrounds/hero-background.jpg"
    title     = "FREQUENTLY ASKED QUESTIONS"
    subtitle  = ""
    q1  = "How often should I get a Brazilian?"
    a1  = "We recommend visiting our studio once every four weeks. Your skin will be less sensitive if you get sugared or waxed regularly."
    q2  = "Will my hair grow back thicker and darker?"
    a2  = "Just the opposite! Hair that is removed at the root grows back softer and finer over time."
    q3  = "Is sugaring safe for those with sensitive skin?"
    a3  = "When done properly, sugaring can be a great benefit to people with sensitive skin. It is much more gentle on the skin than many other methods of hair removal."
    q4  = "Do you treat men?"
    a4  = "Yes! However, we do not offer male Brazilian services at this time."
    q5  = "Can I get a Brazilian on my period?"
    a5  = "Absolutely! We do require you to wear a tampon for sanitary purposes. You may experience discomfort during your service due to hormones."
    q6  = "Is it safe to get a Brazilian while pregnant?"
    a6  = "Yes! Bare in mind you may experience discomfort or pain due to hormones during during pregnancy."

  [params.dosanddonts]
    enable    = true
    background_image      = "images/backgrounds/orchid_yellow_sugar.jpg"
    title     = "DO'S"
    subtitle  = ""
    q1  = "How often should I get a Brazilian?"
    a1  = "We recommend visiting our studio once every four weeks. Your skin will be less sensitive if you get sugared or waxed regularly."
    q2  = "Will my hair grow back thicker and darker?"
    a2  = "Just the opposite! Hair that is removed at the root grows back softer and finer over time."
    q3  = "Is sugaring safe for those with sensitive skin?"
    a3  = "When done properly, sugaring can be a great benefit to people with sensitive skin. It is much more gentle on the skin than many other methods of hair removal."
    q4  = "Do you treat men?"
    a4  = "Yes! However, we do not offer male Brazilian services at this time."
    q5  = "Can I get a Brazilian on my period?"
    a5  = "Absolutely! We do require you to wear a tampon for sanitary purposes. You may experience discomfort during your service due to hormones."
    q6  = "Is it safe to get a Brazilian while pregnant?"
    a6  = "Yes! Bare in mind you may experience discomfort or pain due to hormones during during pregnancy."

  [params.call_to_action]
    enable              = true
    background_image    = "images/backgrounds/cta-background.jpg"
    title               = ""
    primary_button      = "FAQ’S"
    primary_button_url  = "faq"
    secondary_button    = "Book Now"
    secondary_button_url = "services"

  [params.footer]
    # Footer Contact Info
    [params.footer.contactInfo]
      title   = "Contact Info"
      address = "1655 Mansell Rd<br>Alpharetta, GA 30076"
      phone   = "404-201-4919"
      email   = "naomi@sugartimewaxing.com"
      # Footer Sitemap
      [params.footer.sitemap]
        title   = "Sitemap"
        [[params.footer.sitemap.link]]
          name = "About"
          url  = "about"
        [[params.footer.sitemap.link]]
          name = "Services"
          url  = "services"
        [[params.footer.sitemap.link]]
          name = "Faq"
          url  = "faq"
        [[params.footer.sitemap.link]]
          name = "Book Now"
          url  = "contact"
      # Footer Social Media
      [params.footer.social]
        title   = "Social Media"
        [[params.footer.social.link]]
          name = "Instagram"
          url  = "https://www.instagram.com/sugartimewaxing/"
      # Footer Service
      [params.footer.service]
        title       = "We are"
        description = "Obsessed with giving<br>you smooth skin"
