baseURL       = "https://sugarstage.netlify.app/"
languageCode  = "en-us"
title         = "Sugar Time Waxing Studio"
theme         = "roxo"
summarylength = 25

# Site Menus
[menu]
    # Navbar Menus
    [[menu.nav]]
        name    = "Home"
        url     = ""
        weight  = 1
    [[menu.nav]]
        name    = "About"
        url     = "about"
        weight  = 2
    [[menu.nav]]
        name    = "Services"
        url     = "services"
        weight  = 3
    [[menu.nav]]
        name    = "FAQ's"
        url     = "faq"
        weight  = 4
    [[menu.nav]]
        name    = "Book Now"
        url     = "contact"
        weight  = 5

# Site Params
[params]
  logo = "images/logo.png"
  dateFormat = "26 FEB 1994"
  # Meta data
  description = "Sugar Time Waxing Studio"
  author = "Sugar Time"
  # Google Analitycs
  googleAnalitycsID = "Your ID"
  # We're using formspree.io for form handling, paste your formspree url below
  formspreeFormUrl  = "https://formspree.io/myykjpje"

  # Contact Form
  [params.contactForm]
    placeholder_first_name        = "First Name"
    placeholder_last_name         = "Last Name"
    placeholder_email             = "Email"
    placeholder_project_type      = "Project Type"
    placeholder_about_the_project = "About the Project"
    send_message                  = "Send Message"

    [[params.contactForm.projectType]]
      value = "gd"
      title  = "Graphics Design"
    [[params.contactForm.projectType]]
      value = "wd"
      title  = "Web Design"

  # Navbar Action Button
  [params.navAction]
    status  = true
    name    = "Book Now"
    url     = "contact"

  [params.banner]
    enable                = true
    background_image      = "images/backgrounds/hero-background.jpg"
    heading               = "A clean, organic, hair removal studio providing a pleasant & comfortable experience"
    tagline               = ""
    primary_button        = "Do’s & Dont’s"
    primary_button_url    = "services"
    secondary_button      = "Book Appt"
    secondary_button_url  = "contact"

  [params.services]
    enable    = true
    background_image    = "images/backgrounds/hero-background.jpg"
    title     = "FREQUENTLY ASKED QUESTIONS"
    subtitle  = ""
    q1  = "How often should I get a Brazilian?"
    a1  = "We recommend visiting our studio once every four weeks. Your skin will be less sensitive if you get sugared or waxed regularly."

  [params.call_to_action]
    enable              = true
    background_image    = "images/backgrounds/cta-background.jpg"
    title               = ""
    primary_button      = "FAQ’S"
    primary_button_url  = "faq"
    secondary_button    = "Book Now"
    secondary_button_url = "services"

  [params.footer]
    # Footer Contact Info
    [params.footer.contactInfo]
      title   = "Contact Info"
      address = "713 Elmwood St.<br>Prior Lake, MN 55372"
      phone   = "409-896-1444"
      email   = "info@roxo.co"
      # Footer Sitemap
      [params.footer.sitemap]
        title   = "Sitemap"
        [[params.footer.sitemap.link]]
          name = "About Company"
          url  = "about"
        [[params.footer.sitemap.link]]
          name = "Projects"
          url  = "services"
        [[params.footer.sitemap.link]]
          name = "Faq"
          url  = "faq"
        [[params.footer.sitemap.link]]
          name = "Contact"
          url  = "contact"
      # Footer Social Media
      [params.footer.social]
        title   = "Social Media"
        [[params.footer.social.link]]
          name = "Medium"
          url  = "#"
        [[params.footer.social.link]]
          name = "Behance"
          url  = "#"
        [[params.footer.social.link]]
          name = "Dribbble"
          url  = "#"
        [[params.footer.social.link]]
          name = "Instagram"
          url  = "#"
      # Footer Service
      [params.footer.service]
        title       = "We help brands:"
        description = "develop design solutions<br>produce valuable cultural content<br>create fresh brand experience"
